name: Publish Package

on:
  release:
    types: [created]

jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning GitHub Repository
        uses: actions/checkout@v3

      - name: Setting up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: yarn run test

  publish-package:
    needs: test-package
    runs-on: ubuntu-latest
    steps:
      - name: Cloning GitHub Repository
        uses: actions/checkout@v3
        
      - name: Setting up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
